const slimesRancher2 = [
  {
    id: '01',
    name: 'Slime Rosa',
    food: 'Todo',
    diet: 'Omnívoro',
    slimeType: 'Docil',
    favoriteToy: 'Pelota',
    image: 'https://static.wikia.nocookie.net/slimerancher/images/e/e0/SlimePinkSR2.png/revision/latest?cb=20220922201720',  
    game: 'Slime Rancher 2', 
  },
  {
      id: '02',
      name: 'Slime Fósforo',
      food: 'Frutas',
      diet: 'Frugívoro',
      slimeType: 'Docil',
      favoriteToy: 'Lampara',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/8/81/SlimePhosphorSR2.png/revision/latest?cb=20220922201712',  
      game: 'Slime Rancher 2', 
    },
    {
      id: '03',
      name: 'Slime Roca',
      food: 'Vegetales',
      diet: 'Herbívoro',
      slimeType: 'Dañino',
      favoriteToy: 'Tambor',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/4/4e/SlimeRockSR2.png/revision/latest?cb=20220922201744', 
      game: 'Slime Rancher 2',
    },
    {
      id: '04',
      name: 'Slime Miel',
      food: 'Frutas',
      diet: 'Frugívoro',
      slimeType: 'Docil',
      favoriteToy: 'Abeja',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/f/f8/SlimeHoneySR2.png/revision/latest?cb=20220922201637', 
      game: 'Slime Rancher 2',
    },
    {
      id: '05',
      name: 'Slime Atigrado',
      food: 'Carne',
      diet: 'Carnívoro',
      slimeType: 'Docil',
      favoriteToy: 'Ovillo de lana',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/a/a2/SlimeTabbySR2.png/revision/latest?cb=20220922201751', 
      game: 'Slime Rancher 2',
    },
    {
      id: '06',
      name: 'Slime Charco',
      food: 'Agua',
      diet: 'Omnívoro',
      slimeType: 'Docil',
      favoriteToy: 'Patito',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/9/9e/SlimePuddleSR2.png/revision/latest?cb=20220922201728',  
      game: 'Slime Rancher 2', 
    },
    {
      id: '07',
      name: 'Slime Cazador',
      food: 'Carne',
      diet: 'Carnívoro',
      slimeType: 'Docil',
      favoriteToy: 'Peluche de gallina',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/1/1e/SlimeHunterSR2.png/revision/latest?cb=20220922201647',  
      game: 'Slime Rancher 2', 
    },
    {
      id: '08',
      name: 'Slime Algodón',
      food: 'Vegetales',
      diet: 'Herbívoro',
      slimeType: 'Docil',
      favoriteToy: 'Pelota',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/3/3c/SlimeCottonSR2.png/revision/latest?cb=20220922201549',  
      game: 'Slime Rancher 2',
    },
    {
      id: '09',
      name: 'Slime Derviche',
      food: 'Frutas',
      diet: 'Frugívoro',
      slimeType: 'Elemental',
      favoriteToy: 'Torbellino',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/e/e5/IconSlimeDervishSR2.png/revision/latest?cb=20220929193455', 
      game: 'Slime Rancher 2', 
    },
    {
      id: '010',
      name: 'Slime Enredado',
      food: 'Vegetales',
      diet: 'Herbívoro',
      slimeType: 'Normal',
      favoriteToy: 'Pelota con Flores',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/1/15/IconSlimeTangleSR2.png/revision/latest?cb=20231118180241',  
      game: 'Slime Rancher 2', 
    },
    {
      id: '011',
      name: 'Slime Sable',
      food: 'Carne',
      diet: 'Carnívoro',
      slimeType: 'Normal',
      favoriteToy: 'Peluche de Estego',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/7/70/IconSlimeSaberSR2.png/revision/latest?cb=20230218181101',  
      game: 'Slime Rancher 2',
    },
    {
      id: '012',
      name: 'Slime Explosivo',
      food: 'Carne',
      diet: 'Carnívoro',
      slimeType: 'Explosivo',
      favoriteToy: 'Pelota Bomba',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/1/14/SlimeBoomSR2.png/revision/latest?cb=20220922201543', 
      game: 'Slime Rancher 2', 
    },
    {
      id: '013',
      name: 'Slime Cristal',
      food: 'Vegetales',
      diet: 'Herbívoro',
      slimeType: 'Normal',
      favoriteToy: 'Pelota de Cristal',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/1/16/SlimeCrystalSR2.png/revision/latest?cb=20220922201556', 
      game: 'Slime Rancher 2',
    },
    {
      id: '014',
      name: 'Slime Fuego',
      food: 'Cenizas',
      diet: 'Cenizas',
      slimeType: 'Elemental',
      favoriteToy: 'Antorcha',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/5/5c/SlimeFireSR2.png/revision/latest?cb=20220922201605',  
      game: 'Slime Rancher 2',
    },
    {
      id: '015',
      name: 'Slime Dorado',
      food: '❌',
      diet: '❌',
      slimeType: 'Especial',
      favoriteToy: '❌',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/6/6a/SlimeGoldSR2.png/revision/latest?cb=20220922201628',  
      game: 'Slime Rancher 2', 
    },
    {
      id: '016',
      name: 'Slime de la Suerte',
      food: 'Carne',
      diet: 'Carnívoro',
      slimeType: 'Especial',
      favoriteToy: '❌',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/4/41/SlimeLuckySR2.png/revision/latest?cb=20220922201656',  
      game: 'Slime Rancher 2', 
    },
    {
      id: '017',
      name: 'Slime Revoleteador',
      food: 'Nectare',
      diet: 'Nectarívoro',
      slimeType: '  Docil',
      favoriteToy: 'Peluche de oruga',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/e/e2/SlimeFlutterSR2.png/revision/latest?cb=20220922201612',  
      game: 'Slime Rancher 2', 
    },
    {
      id: '018',
      name: 'Slime Murcielago',
      food: 'Frutas',
      diet: 'Frugívoro',
      slimeType: ' Docil',
      favoriteToy: 'Peluche de oruga',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/b/b5/SlimeBattySR2.png/revision/latest?cb=20220922201535', 
      game: 'Slime Rancher 2',
    },
    {
      id: '019',
      name: 'Slime Pescador',
      food: 'Carne',
      diet: 'Carnívoro',
      slimeType: ' Docil',
      favoriteToy: 'Pelota',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/8/8f/SlimeAnglerSR2.png/revision/latest?cb=20220922201529', 
      game: 'Slime Rancher 2', 
    },
    {
      id: '020',
      name: 'Slime Cola Anillada',
      food: 'Todo',
      diet: 'Omnívoro',
      slimeType: 'Docil',
      favoriteToy: 'Cubo de basura',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/e/ed/SlimeRingtailSR2.png/revision/latest?cb=20220922201737', 
      game: 'Slime Rancher 2', 
    },
    {
      id: '021',
      name: 'Slime Yema',
      food: '❌',
      diet: '❌',
      slimeType: 'Docil',
      favoriteToy: 'Cubo de basura',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/a/ac/SlimeYolkySR2.png/revision/latest?cb=20230216213335', 
      game: 'Slime Rancher 2',
    },
    {
      id: '022',
      name: 'Slime Gemelo',
      food: 'Frutas',
      diet: 'Frugívoro',
      slimeType: 'Docil',
      favoriteToy: '❌',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/5/59/SlimeTwinSR2.png/revision/latest?cb=20241212184432', 
      game: 'Slime Rancher 2', 
    },
    {
      id: '023',
      name: 'Slime Babosa',
      food: 'Carne',
      diet: 'Carnívoro',
      slimeType: 'Docil',
      favoriteToy: '❌',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/1/13/SlimeSloomberSR2.png/revision/latest?cb=20241212183024', 
      game: 'Slime Rancher 2', 
    },
    {
      id: '024',
      name: 'Slime Sombra',
      food: '❌',
      diet: '❌',
      slimeType: 'Especial',
      favoriteToy: '❌',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/a/a7/SlimeShadowSR2.png/revision/latest?cb=20241212184407', 
      game: 'Slime Rancher 2', 
    },
    {
      id: '025',
      name: 'Slime ¨El alquitrán¨',
      food: 'Carne / Slimes',
      diet: 'Carnívoro',
      slimeType: ' Docil',
      favoriteToy: 'Pelota',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/7/75/SlimeTarrSR2.png/revision/latest?cb=20220922201758', 
      game: 'Slime Rancher 2', 
    },
];

export default slimesRancher2;
