const slimesRancher1 = [
    {
      id: '1',
      name: 'Slime Rosa',
      food: 'Todo',
      diet: 'Omnívoro',
      slimeType: 'Docil',
      favoriteToy: 'Pelota',
      image: 'https://static.wikia.nocookie.net/slimerancher/images/6/6c/Pink_Slime_SP.png/revision/latest/scale-to-width-down/1000?cb=20170401125704',  
      game: 'Slime Rancher 1', 
    },
    {
        id: '2',
        name: 'Slime Fósforo',
        food: 'Frutas',
        diet: 'Frugívoro',
        slimeType: 'Docil',
        favoriteToy: 'Lampara',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/e/ee/Phosphor_Slime_SP.png/revision/latest?cb=20241012175004',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '3',
        name: 'Slime Roca',
        food: 'Vegetales',
        diet: 'Herbívoro',
        slimeType: 'Normal',
        favoriteToy: 'Tambor',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/9/90/Rock_Slime_SP.png/revision/latest?cb=20241012172843',  
        game: 'Slime Rancher 1',
      },
      {
        id: '4',
        name: 'Slime Miel',
        food: 'Frutas',
        diet: 'Frugívoro',
        slimeType: 'Docil',
        favoriteToy: 'Abeja',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/b/b6/Honey_Slime_SP.png/revision/latest/scale-to-width-down/1000?cb=20241012181009',  
        game: 'Slime Rancher 1',
      },
      {
        id: '5',
        name: 'Slime Atigrado',
        food: 'Carne',
        diet: 'Carnívoro',
        slimeType: 'Docil',
        favoriteToy: 'Ovillo de lana',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/9/94/Tabby_Slime_SP.png/revision/latest?cb=20241012175535',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '6',
        name: 'Slime Charco',
        food: 'Agua',
        diet: 'Omnívoro',
        slimeType: 'Docil',
        favoriteToy: 'Patito',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/9/97/Puddle_Slime_SP.png/revision/latest?cb=20241012181743',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '7',
        name: 'Slime Cazador',
        food: 'Carne',
        diet: 'Carnívoro',
        slimeType: 'Docil',
        favoriteToy: 'Peluche de gallina',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/b/b7/Hunter_Slime_SP.png/revision/latest?cb=20241012190129',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '8',
        name: 'Slime Cuántico',
        food: 'Frutas',
        diet: 'Frugívoro',
        slimeType: 'Temporal',
        favoriteToy: 'Cubo de Rubik',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/7/79/Quantum_Slime_SP.png/revision/latest?cb=20170401125800',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '9',
        name: 'Slime Derviche',
        food: 'Frutas',
        diet: 'Frugívoro',
        slimeType: 'Elemental',
        favoriteToy: 'Torbellino',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/5/50/Dervish_Slime_SP.png/revision/latest?cb=20221221183332',  
        game: 'Slime Rancher 1',
      },
      {
        id: '10',
        name: 'Slime Enredado',
        food: 'Vegetales',
        diet: 'Herbívoro',
        slimeType: 'Normal',
        favoriteToy: 'Pelota con Flores',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/d/d6/Tangle_Slime_SP.png/revision/latest?cb=20241114191939',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '11',
        name: 'Slime Sable',
        food: 'Carne',
        diet: 'Carnívoro',
        slimeType: 'Normal',
        favoriteToy: 'Peluche de Estego',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/a/a6/Saber_Slime_SP.png/revision/latest?cb=20241114195235',  
        game: 'Slime Rancher 1',
      },
      {
        id: '12',
        name: 'Slime Radiactivo',
        food: 'Vegetales',
        diet: 'Herbívoro',
        slimeType: 'Normal',
        favoriteToy: 'Bateria',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/b/b2/Rad_Slime_SP.png/revision/latest?cb=20170401125707',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '13',
        name: 'Slime Explosivo',
        food: 'Carne',
        diet: 'Carnívoro',
        slimeType: 'Explosivo',
        favoriteToy: 'Pelota Bomba',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/6/66/Boom_Slime_SP.png/revision/latest?cb=20170401125706', 
        game: 'Slime Rancher 1', 
      },
      {
        id: '14',
        name: 'Slime Cristal',
        food: 'Vegetales',
        diet: 'Herbívoro',
        slimeType: 'Normal',
        favoriteToy: 'Pelota de Cristal',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/4/4a/Crystal_Slime_SP.png/revision/latest?cb=20241012184426', 
        game: 'Slime Rancher 1',
      },
      {
        id: '15',
        name: 'Slime Fuego',
        food: 'Cenizas',
        diet: 'Cenizas',
        slimeType: 'Elemental',
        favoriteToy: 'Antorcha',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/5/58/Fire_Slime_SP.png/revision/latest?cb=20241012190609',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '16',
        name: 'Slime Mosaico',
        food: 'Frutas',
        diet: 'Frugívoro',
        slimeType: 'Normal',
        favoriteToy: 'Bola de disco',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/6/69/Mosaic_Slime_SP.png/revision/latest?cb=20241012191102', 
        game: 'Slime Rancher 1', 
      },
      {
        id: '17',
        name: 'Slime Mercurio',
        food: 'Electricidad',
        diet: 'Voltaica',
        slimeType: 'Dañino / Especial',
        favoriteToy: '❌',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/d/d1/Quicksilver_Slime_SP.png/revision/latest?cb=20241012194237',  
        game: 'Slime Rancher 1',
      },  
      {
        id: '18',
        name: 'Slime Fallo',
        food: '❌',
        diet: '❌',
        slimeType: 'Docil / Especial',
        favoriteToy: '❌',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/9/92/Glitch_Slime_SP.png/revision/latest?cb=20241012200249',  
        game: 'Slime Rancher 1',
      },
      {
        id: '19',
        name: 'Slime Dorado',
        food: 'Vegetales',
        diet: 'Herbívoro',
        slimeType: 'Especial',
        favoriteToy: '❌',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/6/67/Gold_Slime_SP.png/revision/latest?cb=20241012201616',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '20',
        name: 'Slime de la Suerte',
        food: 'Carne',
        diet: 'Carnívoro',
        slimeType: 'Especial',
        favoriteToy: '❌',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/6/6a/Lucky_Slime_SP.png/revision/latest?cb=20170401125804',  
        game: 'Slime Rancher 1', 
      },
      {
        id: '21',
        name: 'Slime centelleante',
        food: 'Todo',
        diet: '❌',
        slimeType: 'Docil / Especial',
        favoriteToy: '❌',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/b/b4/Twinkle_Slime_SP.png/revision/latest?cb=20190924192504',  
        game: 'Slime Rancher 1', 
      },   
      {
        id: '22',
        name: 'Slime Fiesta',
        food: 'Todo',
        diet: 'Omnívoro',
        slimeType: 'Docil',
        favoriteToy: '❌',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/8/8c/Party_Gordo_SP.png/revision/latest?cb=20180523125059',  
        game: 'Slime Rancher 1',
      },
      {
        id: '23',
        name: 'Slime ¨El alquitrán¨',
        food: 'Carne / Slimes',
        diet: 'Carnívoro',
        slimeType: 'Hostil',
        favoriteToy: '❌',
        image: 'https://static.wikia.nocookie.net/slimerancher/images/7/75/SlimeTarrSR2.png/revision/latest?cb=20220922201758',  
        game: 'Slime Rancher 1',
      },
  ];
  
  export default slimesRancher1;
  
